document.getElementById('region').addEventListener('change', function () {
  const region = this.value;
  const districtSelect = document.getElementById('district');

  const districts = {
      "AHAFO": ["ASUNAFO NORTH", "ASUNAFO SOUTH", "ASUTIFI NORTH", "ASUTIFI SOUTH", "TANO NORTH", "TANO SOUTH"],
      "ASHANTI": ["ADANSI ASOKWA", "ADANSI NORTH", "ADANSI SOUTH", "AFIGYA KWABRE NORTH", "AFIGYA KWABRE SOUTH", "AHAFO ANO NORTH", "AHAFO ANO SOUTH EAST", "AHAFO ANO SOUTH WEST", "AKROFUOM", "AMANSIE CENTRAL", "AMANSIE SOUTH", "AMANSIE WEST", "ASANTE AKIM CENTRAL", "ASANTE AKIM NORTH", "ASANTE AKIM SOUTH MUNICIPAL", "ASOKORE MAMPONG", "ASOKWA", "ATWIMA KWANWOMA", "ATWIMA MPONUA", "ATWIMA NWABIAGYA NORTH", "ATWIMA NWABIAGYA SOUTH", "BANTAMA", "BEKWAI", "BOSOME FREHO", "BOSOMTWE", "EJISU", "EJURA SEKYEDUMASE", "JUABEN", "KWABRE EAST", "KWADASO MUNICIPAL", "MAMPONG", "MANHYIA", "NHYIAESO", "OBUASI EAST", "OBUASI MUNICIPAL", "OFFINSO MUNICIPAL", "OFFINSO NORTH", "OFORIKROM", "OLD TAFO", "SEKYERE AFRAM PLAINS", "SEKYERE CENTRAL", "SEKYERE EAST", "SEKYERE KUMAWU", "SEKYERE SOUTH", "SUAME", "SUBIN"],
      "BONO": ["BANDA", "BEREKUM EAST", "BEREKUM WEST", "DORMAA CENTRAL", "DORMAA EAST", "DORMAA WEST", "JAMAN NORTH", "JAMAN SOUTH", "SUNYANI", "SUNYANI WEST", "TAIN", "WENCHI"],
      "BONO EAST": ["ATEBUBU-AMANTIN", "KINTAMPO NORTH", "KINTAMPO SOUTH", "NKORANZA NORTH", "NKORANZA SOUTH", "PRU EAST", "PRU WEST", "SENE EAST", "SENE WEST", "TECHIMAN MUNICIPAL", "TECHIMAN NORTH"],
      "CENTRAL": ["ABURA-ASEBU-KWAMANKESE", "AGONA EAST", "AGONA WEST", "AJUMAKO-ENYAN-ESSIAM", "ASIKUMA-ODOBEN-BRAKWA", "ASSIN NORTH", "ASSIN SOUTH", "AWUTU SENYA EAST", "AWUTU SENYA WEST", "CAPE COAST", "EFUTU", "GOMOA CENTRAL", "GOMOA EAST", "GOMOA WEST", "KOMENDA-EDINA-EGUAFO-ABIREM", "MFANTSEMAN", "TWIFO-ATTI MORKWA", "UPPER DENKYIRA EAST", "UPPER DENKYIRA WEST"],
      "EASTERN": ["ABUAKWA NORTH", "ABUAKWA SOUTH", "ACHIASE", "AFRAM PLAINS NORTH", "AFRAM PLAINS SOUTH", "AKWAPIM NORTH", "AKWAPIM SOUTH", "AKYEMANSA", "ASENE-MANSO-AKROSO", "ASUOGYAMAN", "ATIWA EAST", "ATIWA WEST", "AYENSUANO", "BIRIM CENTRAL", "BIRIM NORTH", "BIRIM SOUTH", "DENKYEMBOUR", "FANTEAKWA NORTH", "FANTEAKWA SOUTH", "KWAEBIBIREM", "KWAHU AFRAM PLAINS SOUTH", "KWAHU EAST", "KWAHU SOUTH", "KWAHU WEST", "LOWER MANYA KROBO", "NEW JUABEN NORTH", "NEW JUABEN SOUTH", "NSAWAM ADOAGYIRI", "OKERE", "SUHUM", "UPPER MANYA KROBO", "UPPER WEST AKIM", "YILO KROBO"],
      "GREATER ACCRA": ["ABLEKUMA CENTRAL", "ABLEKUMA NORTH", "ABLEKUMA WEST", "ACCRA METROPOLITAN", "ADA EAST", "ADA WEST", "ADENTA MUNICIPAL", "ASHIEDU KETEKU", "ASHIAMAN MUNICIPAL", "AYAWASO CENTRAL", "AYAWASO EAST", "AYAWASO NORTH", "AYAWASO WEST", "GA CENTRAL", "GA EAST", "GA SOUTH", "GA WEST", "KPONE-KATAMANSO", "KROWOR", "LA DADE-KOTOPON", "LA NKWANTANAN-MADINA", "LEDZOKUKU", "NINGO PRAMPRAM", "OKAIKOI NORTH", "OKAIKOI SOUTH", "SHAI-OSUDOKU", "TEMA METROPOLITAN", "TEMA WEST", "WEIJA GBAWE"],
      "NORTH EAST": ["BUNKPURUGU", "CHEREPONI", "EAST MAMPRUSI", "MAMPRUGU MOAGDURI", "WEST MAMPRUSI", "YUNYOO-NASUAN"],
      "NORTHERN": ["KUMBUNGU", "MION", "NANTON", "SAGNARIGU", "SAVELUGU", "TAMALE METROPOLITAN", "TOLON", "KARAGA", "SABOBA", "SAGNARIGU MUNICIPAL", "SAGNARIGU SOUTH", "TOLON DISTRICT", "YENDI MUNICIPAL"],
      "OTI": ["BIAKOYE", "JASIKAN", "KRACHI EAST", "KRACHI NCHUMURU", "KRACHI WEST", "NKONYA ALAVANYO", "NKONYA BUMBULU", "NKONYA DUDOVI", "NKONYA DUJOUR", "NKONYA NTUMBA", "NKONYA NTUMDA", "NKONYA NTUMDI", "NKONYA TACHI", "NKONYA TAPA", "NKONYA TETI", "NKONYA TOBI", "NKONYA TOFA", "NKONYA TSANKAW", "NKONYA TWUNDI", "NKONYA WURAWURA"],
      "SAVANNAH": ["BUIPE", "DABOYA", "DAMONGO", "KALBA", "KASULIYA", "KATANGA", "KINTAMPO NORTH", "KINTAMPO SOUTH", "KINTAMPO WEST", "KONDOMA", "KONGBE", "SANGBA", "WURUBONGO"],
      "UPPER EAST": ["BOLGATANGA MUNICIPAL", "BOLGATANGA EAST", "BONGO", "BULSA NORTH", "BULSA SOUTH", "GARU", "KASENA NANKANA WEST", "KASENA NANKANA EAST", "NABDAM", "PAGA", "PUSIGA", "TALENSI", "TEMPANE"],
      "UPPER WEST": ["DAFFIAMA BUSSIE ISSA", "JIRAPA", "LAMBUSIE KARMI", "LAWRA", "NANDOM", "NANDOM", "NADOWLI KALEO", "SISSALA EAST", "SISSALA WEST", "WA EAST", "WA MUNICIPAL", "WA WEST"],
      "VOLTA": ["ADAKLU", "AFADZATO SOUTH", "AKATSI NORTH", "AKATSI SOUTH", "ANLOGA", "ANLO WEST", "ANLO WEST CENTRAL", "ANLO WEST MUNICIPAL", "CENTRAL TONGU", "HO MUNICIPAL", "HO WEST", "HOHOE MUNICIPAL", "JASIKAN", "KETU NORTH", "KETU SOUTH", "KETU SOUTH MUNICIPAL", "KETA MUNICIPAL", "KRACHI EAST", "KRACHI WEST", "NORTH DAYI", "NORTH TONGU", "SOUTH DAYI", "SOUTH TONGU"],
      "WESTERN": ["AHANTA WEST", "AOWIN", "BIA EAST", "BIA WEST", "BIBIANI-ANHWIASO-BEKWAI", "ELLEMBELLE", "JOMORO", "JUABOSO", "KWESIMINTSIM", "MPOHOR", "MPOHOR WASSA EAST", "NZEUMA EAST", "NZEUMA WEST", "PRESTEA-HUNI VALLEY", "SEFWI AKONTOMBRA", "SEFWI BODI", "SEFWI WIAWSO", "SEKONDI TAKORADI METROPOLITAN", "SHAMA", "TARKWA NSUAEM", "WASSA AMENFI EAST", "WASSA AMENFI CENTRAL", "WASSA AMENFI WEST", "WASSA EAST"],
      "WESTERN NORTH": ["AOWIN", "BIA EAST", "BIA WEST", "BIBIANI-ANHWIASO-BEKWAI", "JUABOSO", "SEFWI AKONTOMBRA", "SEFWI BODI", "SEFWI WIAWSO"]
  };

  districtSelect.innerHTML = '<option value="">Select District</option>'; // Reset district options
  if (region && districts[region]) {
      districts[region].forEach(district => {
          const option = document.createElement('option');
          option.value = district;
          option.textContent = district;
          districtSelect.appendChild(option);
      });
  }
});
